[package]
name = "backend-data-apply-tracking"
version = "0.1.0"
edition = "2024"

[dependencies]
sqlx = { version = "0.8.6", features = ["sqlite", "macros", "migrate", "runtime-tokio"] }
uuid = { version = "1.19.0", features = ["v4"] }
